### ISSUE TITLE
Heroku build fails

### ISSUE THREAD

**Issue by flabbert** [jaguado/dotnet-buildpack-vs2017#2]
remote: Found 1 csproj files
remote: Building
remote: dotnet restore
remote: MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

what am i doing wrong?

**Comment by jaguado** [comment]
Do you have a project.json or a .csproj in your project directory? Because this buildpack works only with .csproj. Yo can try another dotnetcore buildpack like "https://github.com/jaguado/dotnet-buildpack.git" or try "dotnet migrate".

**Comment by flabbert** [comment]
i found the problem. first, you have to specify the location of the .csproj file with PROJECT config option in heroku, secondly, there seems to be some fault with this particular buildscript, because the herokuinstance crashes immediately when trying to access the webpage. error 145. Asking for the dotnet sdk to be installed, which tells me that the correct .dll was not referenced in the buildscript for starting the app.

**Comment by AlexByte** [comment]
@flabbert What's mean "PROJECT config option in heroku"?

**Comment by NOmSOPWIM** [comment]
@AlexByte It's a Variable you create on heroku config vars on settings
